### ISSUE TITLE
Field length validations for response data is incorrect

### ISSUE THREAD

**Issue by shivang-crest** [CyberSource/cybersource-rest-client-python#23]
Currently, the SDK throws ValueError in many cases especially for length validations.
In one case, the Transactions Summaries' deviceInformation IP Address is expecting 15 as max length(considering IPv4). However we are also getting IPv6 from response, resulting in Value Error.

In certain cases the validation of payment solution also fails for length validation(expected should be less than 12)

**Comment by huynhr** [comment]
I am also having a similar issue. This happens when I try to retrieve transaction details. I get back this error: ValueError: Invalid value for `payment_solution`, length must be less than or equal to `12`.

Currently happens when the payment solution is `Alternative Payment AliPay` and ` American Express`(Any other payment solution that is greater than 12).

**Comment by monu-kumar-visa** [comment]
The check for minimum and maximum length from the models has been removed in version 0.0.23 and all subsequent versions.
